### ISSUE TITLE
builds break

### ISSUE THREAD

**Issue by justinbmeyer** [bitovi/documentjs#210]
The travis build seems to break even though it passes locally on my mac.  

https://travis-ci.org/bitovi/documentjs/builds/83233336

**Comment by daffl** [comment]
It's NodeJS 4.0. The error seems to be in engine-dependencies:

```
/home/travis/build/bitovi/documentjs/node_modules/engine-dependencies/engine-dependencies.js:45
	var exampleDepType = Object.keys(dependencyOptions)[0];
	                            ^
TypeError: Cannot convert undefined or null to object
    at Function.keys (native)
    at engineDependencies (/home/travis/build/bitovi/documentjs/node_modules/engine-dependencies/engine-dependencies.js:45:30)
    at Object.<anonymous> (/home/travis/build/bitovi/documentjs/node_modules/engine-dependencies/bin/install-engine-dependencies:22:1)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:475:10)
    at startup (node.js:117:18)
    at node.js:951:3
```
