### ISSUE TITLE
DocumentJS 0.4.4 doesn’t work on Node 0.10.36

### ISSUE THREAD

**Issue by chasenlehara** [bitovi/documentjs#262]
I have a project that works with 0.4.3, but when I upgrade to 0.4.4, I see this error:

```
TypeError: Object function Symbol(description) {
      var value = new SymbolValue(description);
      if (!(this instanceof Symbol))
        return value;
      throw new TypeError('Symbol cannot be new\'ed');
    } has no method 'for'
    at makeSymbol (~/my-project/node_modules/documentjs/node_modules/cross-spawn-async/node_modules/lru-cache/lib/lru-cache.js:18:22)
    at priv (~/my-project/node_modules/documentjs/node_modules/cross-spawn-async/node_modules/lru-cache/lib/lru-cache.js:31:11)
    at new LRUCache (~/my-project/node_modules/documentjs/node_modules/cross-spawn-async/node_modules/lru-cache/lib/lru-cache.js:65:13)
    at Object.<anonymous> (~/my-project/node_modules/documentjs/node_modules/cross-spawn-async/lib/resolveCommand.js:7:20)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
```

It seems like this incompatibility was introduced with https://github.com/bitovi/documentjs/pull/247 when the [`cross-spawn-async`](https://www.npmjs.com/package/cross-spawn-async) package was added.

**Comment by matthewp** [comment]
If you look in `node_modules/documentjs/node_modules/cross-spawn-async/node_modules/lru-cache` and look in its package.json, what version do you see there?

**Comment by chasenlehara** [comment]
`4.0.1`, which makes sense given [cross-spawn-async’s package.json](https://github.com/IndigoUnited/node-cross-spawn-async/blob/e6aafdec18d34fd2c4c355c79df6a1319e447a78/package.json#L34)
