### ISSUE TITLE
v0.5.1 breaks on execution due to deprecated package`

### ISSUE THREAD

**Issue by mjstahl** [bitovi/documentjs#280]
It appears that documentjs is attempting to use `can-event-radiochange` instead of `can-event-dom-radiochange`.

This affects both the locally and globally installed versions of v0.5.1.

```
/Users/mark/.nvm/versions/node/v6.11.2/lib/node_modules/documentjs/node_modules/q/q.js:126
                    throw e;
                    ^

Error: Cannot find module 'can-event-radiochange'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.resolve (internal/module.js:27:19)
    at module.exports (/Users/mark/.nvm/versions/node/v6.11.2/lib/node_modules/documentjs/site/static/build/61b8b69214de60e11ccf85f6dd366960/build.js:45:28)
    at ./Users/mark/.nvm/versions/node/v6.11.2/lib/node_modules/documentjs/lib/generators/html/build/static_dist.js:92:11
    at _fulfilled (/Users/mark/.nvm/versions/node/v6.11.2/lib/node_modules/documentjs/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/Users/mark/.nvm/versions/node/v6.11.2/lib/node_modules/documentjs/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/Users/mark/.nvm/versions/node/v6.11.2/lib/node_modules/documentjs/node_modules/q/q.js:749:13)
    at /Users/mark/.nvm/versions/node/v6.11.2/lib/node_modules/documentjs/node_modules/q/q.js:557:44
    at flush (/Users/mark/.nvm/versions/node/v6.11.2/lib/node_modules/documentjs/node_modules/q/q.js:108:17)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```

**Comment by kylegifford** [comment]
![image](https://user-images.githubusercontent.com/4341379/30288694-e956ce58-96e6-11e7-98ce-dc8e957483d9.png)

**Comment by chasenlehara** [comment]
I fixed this issue by publishing `can-event-radiochange@0.1.2` with this fix: https://github.com/canjs/can-event-radiochange/commit/dea422187530d77830bd3431b782e7b1d59ceadf
