### ISSUE TITLE
TypeError: Cannot read property 'order' of undefined

### ISSUE THREAD

**Issue by trusktr** [bitovi/documentjs#93]
I'm running `documentjs` in the root of my project and it's erroring with

```
 ❯ documentjs                                                                                                                                                                            [21:00:21]
No documentjs.json. Create one to configure its behavior.
Generating docs at ../docs
FIND: README.md
FIND: Calendar.js
FIND: Cube.js
FIND: DoubleSidedPlane.js
FIND: Grid.js
FIND: Molecule.js
FIND: Plane.js
FIND: PushMenuLayout.js
FIND: global.js
FIND: infamous.js
FIND: utils.js
BUILD: Using cache documentjs/site/templates/99914b932bd37a50b983c5e7c90ae93b
FIND: src/Calendar.js
FIND: src/Cube.js
FIND: src/DoubleSidedPlane.js
FIND: src/Grid.js
FIND: src/Molecule.js
FIND: src/Plane.js
FIND: src/PushMenuLayout.js
FIND: src/utils.js
Guessed parent 'README'. Set parent in your siteConfig.
OUT: ../docs/index.html
BUILD: Getting build module
OPENING: static
error { [Error: ENOENT, open '/usr/local/lib/node_modules/documentjs/node_modules/canjs/control/control.js']
  errno: 34,
  code: 'ENOENT',
  path: '/usr/local/lib/node_modules/documentjs/node_modules/canjs/control/control.js' } Error: ENOENT, open '/usr/local/lib/node_modules/documentjs/node_modules/canjs/control/control.js'
ERROR: Cannot read property 'order' of undefined TypeError: Cannot read property 'order' of undefined
    at visit (/usr/local/lib/node_modules/documentjs/node_modules/steal-tools/lib/graph/order.js:7:12)
    at /usr/local/lib/node_modules/documentjs/node_modules/steal-tools/lib/graph/order.js:11:5
    at Array.forEach (native)
    at visit (/usr/local/lib/node_modules/documentjs/node_modules/steal-tools/lib/graph/order.js:10:22)
    at /usr/local/lib/node_modules/documentjs/node_modules/steal-tools/lib/graph/order.js:11:5
    at Array.forEach (native)
    at visit (/usr/local/lib/node_modules/documentjs/node_modules/steal-tools/lib/graph/order.js:10:22)
    at module.exports (/usr/local/lib/node_modules/documentjs/node_modules/steal-tools/lib/graph/order.js:16:2)
    at /usr/local/lib/node_modules/documentjs/node_modules/steal-tools/lib/build/multi.js:116:4
    at Array.forEach (native)

/usr/local/lib/node_modules/documentjs/node_modules/q/q.js:126
                    throw e;
                          ^
TypeError: Cannot read property 'order' of undefined
    at visit (/usr/local/lib/node_modules/documentjs/node_modules/steal-tools/lib/graph/order.js:7:12)
    at /usr/local/lib/node_modules/documentjs/node_modules/steal-tools/lib/graph/order.js:11:5
    at Array.forEach (native)
    at visit (/usr/local/lib/node_modules/documentjs/node_modules/steal-tools/lib/graph/order.js:10:22)
    at /usr/local/lib/node_modules/documentjs/node_modules/steal-tools/lib/graph/order.js:11:5
    at Array.forEach (native)
    at visit (/usr/local/lib/node_modules/documentjs/node_modules/steal-tools/lib/graph/order.js:10:22)
    at module.exports (/usr/local/lib/node_modules/documentjs/node_modules/steal-tools/lib/graph/order.js:16:2)
    at /usr/local/lib/node_modules/documentjs/node_modules/steal-tools/lib/build/multi.js:116:4
    at Array.forEach (native)
```

**Comment by justinbmeyer** [comment]
I'll fix this Monday.

**Comment by trusktr** [comment]
Sweeet. looking forward to getting docs running!

**Comment by justinbmeyer** [comment]
@trusktr Please try `documentjs: "0.2.1"` and let me know what happens.  Thanks!

**Comment by trusktr** [comment]
This works now, which brought me to #95. :D
